//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sculptor.Gynac.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionMaster
    {
        public QuestionMaster()
        {
            this.QuetionOptionMasters = new HashSet<QuetionOptionMaster>();
            this.UserAnswers = new HashSet<UserAnswer>();
        }
    
        public int Id { get; set; }
        public string Question { get; set; }
        public string Ans { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> TalkId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual TalkMaster TalkMaster { get; set; }
        public virtual ICollection<QuetionOptionMaster> QuetionOptionMasters { get; set; }
        public virtual ICollection<UserAnswer> UserAnswers { get; set; }
    }
}
